name: "SFDX Scan Pull Request"
description: "Executes SFDX Scanner on the scope of a pull request, translates the findings into in-line comments."
inputs:
  category:
    description: "Categor(ies) of rules to run."
  engine:
    description: "Engine(s) to run."
  eslint-env:
    description: "JSON-formatted string, overrides ESLint's default environment variables."
  eslintconfig:
    description: "Location of eslintrc config to customize eslint engine."
  pmdconfig:
    description: "Location of PMD rule reference XML file to customize rule selection."
  severity-threshold:
    description: "Integer threshold value which will throw an error when violations of specific severity (or more severe) are detected."
  strictly-enforced-rules:
    description: "JSON string which contains the rules which will be strictly enforced regardless of their priority. Enforced rules are identified by their engine, category, and rule name."
  tsconfig:
    description: "Location of tsconfig.json file."
  commit-sha:
    description: "Commit sha"
  report-mode:
    description: "Use comments or check-runs for reporting errors"
    default: 'check-runs'
  delete-resolved-comments:
    description: "Delete comments once the issue has been resolved"
    default: true
runs:
  using: "node16"
  main: "index.js"
