name: test

on:
  pull_request:
    branches: [main]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli -g
          sfdx plugins:install @salesforce/sfdx-scanner

      - name: Apex static analysis
        uses: ./
        with:
          pmdconfig: apex-ruleset.xml
          severity-threshold: 4
