name: test

on:
  pull_request:
    branches: [main]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Apex static analysis
        uses: ./
        with:
          pmdconfig: apex-ruleset.xml
          severity-threshold: 4
